name: CI/CD - Docker Compose Build and Push

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images with Docker Compose
        run: |
          docker-compose build

      - name: Tag and Push Frontend Image
        run: |
          docker tag assignment-5-frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest

      - name: Tag and Push Backend Image
        run: |
          docker tag assignment-5-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest

      - name: Generate SBOM for Frontend
        uses: anchore/sbom-action@v0
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest
          format: cyclonedx-json
          output-file: sbom-frontend.json

      - name: Generate SBOM for Backend
        uses: anchore/sbom-action@v0
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest
          format: cyclonedx-json
          output-file: sbom-backend.json

      - name: Upload SBOM Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sboms
          path: |
            sbom-frontend.json
            sbom-backend.json
